MAKE = make
CXX = g++
CXXFLAGS = -Wall -std=c++11 -Wno-deprecated
OPTFLAGS = -O3
#DEBUG = -g
OTHERLIBS = ../
INCFLAGS = -I../lib -I$(OTHERLIBS)
LINKFLAGS = -L../lib -lmoletools 
BINDIR = ../bin
LIBEXT=a
